name: Code Quality

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest
          composer dump-autoload
          
      - name: Setup test config
        run: |
          mkdir -p config/autoload
          cp publish/mqtt.php config/autoload/mqtt.php
        
      - name: Check code style
        run: composer cs-fix -- --dry-run --diff