name: Integration Tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  mqtt-integration:
    runs-on: ubuntu-latest
    services:
      emqx:
        image: emqx/emqx:5.7
        ports:
          - 1883:1883
          - 8083:8083
          - 8084:8084
        env:
          EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
          EMQX_ALLOW_ANONYMOUS: "true"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: swoole
          
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest
          composer dump-autoload
        
      - name: Wait for EMQX
        run: |
          timeout 60 bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/$0/$1; do sleep 1; done' localhost 1883
          timeout 60 bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/$0/$1; do sleep 1; done' localhost 8083
          
      - name: Test MQTT 5 features
        run: |
          MQTT_HOST=localhost MQTT_PORT=1883 MQTT_PROTOCOL_LEVEL=5 composer test
          
      - name: Test shared subscriptions
        run: |
          MQTT_HOST=localhost MQTT_PORT=1883 composer test -- --filter=SharedSubscription
          
      - name: Test queue subscriptions  
        run: |
          MQTT_HOST=localhost MQTT_PORT=1883 composer test -- --filter=QueueSubscription