name: MQTT 5 Features

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  mqtt5-features:
    runs-on: ubuntu-latest
    services:
      emqx:
        image: emqx/emqx:5.7
        ports:
          - 1883:1883
          - 8083:8083
        env:
          EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
          EMQX_ALLOW_ANONYMOUS: "true"
          EMQX_MQTT__SHARED_SUBSCRIPTION: "true"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: swoole
          
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest
          composer dump-autoload
          
      - name: Setup test config
        run: |
          mkdir -p config/autoload
          cp publish/mqtt.php config/autoload/mqtt.php
        
      - name: Wait for EMQX
        run: |
          timeout 60 bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/$0/$1; do sleep 1; done' localhost 1883
          
      - name: Verify EMQX MQTT 5 support
        run: |
          curl -f http://localhost:8083/api/v5/status || exit 1
          
      - name: Test shared subscription load balancing
        run: |
          MQTT_HOST=localhost MQTT_PORT=1883 composer test -- --filter=SharedSubscriptionLoadBalance
          
      - name: Test MQTT 5 properties
        run: |
          MQTT_HOST=localhost MQTT_PORT=1883 composer test -- --filter=MQTT5Properties